### ISSUE TITLE
InvocationTargetException when using ModLauncher with OpenLauncherLib

### ISSUE THREAD

**Issue by kerwanp** [cpw/modlauncher#26]
I'm currently working on a custom Minecraft Launcher for MC1.13.2 with Forge.
I got a lot of problems when doing it, but I approach the goal.

When i try to run ModLauncher, i'm getting this error :
```
Exception in thread "Client thread" [08:22:33.652] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[08:22:33.652] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:21)
[08:22:33.652] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:57)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:43)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.IncompatibleClassChangeError: vtable stub
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.EnumProperty.func_177708_a(SourceFile:75)
[08:22:33.653] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.EnumProperty.func_177709_a(SourceFile:71)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.properties.BlockStateProperties.<clinit>(SourceFile:38)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.fluid.FlowingFluid.<clinit>(SourceFile:34)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.fluid.Fluid.func_207195_i(Fluid.java:104)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:404)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:334)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:144)
[08:22:33.654] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 10 more
```

After some search i found an answer who say that he haven't the error with the JVM argument `-Xin`. But i'm still getting an almost identical error message :
```
Exception in thread "Client thread" [08:25:57.412] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[08:25:57.412] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:21)
[08:25:57.412] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
[08:25:57.413] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
[08:25:57.413] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:57)
[08:25:57.413] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:43)
[08:25:57.413] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[08:25:57.413] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
[08:25:57.414] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.IncompatibleClassChangeError
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[08:25:57.415] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.EnumProperty.func_177708_a(SourceFile:75)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.EnumProperty.func_177709_a(SourceFile:71)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.state.properties.BlockStateProperties.<clinit>(SourceFile:38)
[08:25:57.416] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.fluid.FlowingFluid.<clinit>(SourceFile:34)
[08:25:57.417] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.fluid.Fluid.func_207195_i(Fluid.java:104)
[08:25:57.417] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:404)
[08:25:57.417] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:334)
[08:25:57.417] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:144)
[08:25:57.417] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 10 more
```

Java Version : 1.8.0_212
MC Version : 1.13.2
Forge Version : 1.13.2-25.0.215

> I'm using Livartan OpenLauncherLib

I really hope you have an idea on how to fix that and why is it happening !

Thanks in advance.

**Comment by cpw** [comment]
It looks like you should talk to OpenLauncherLib. It doesn't appear to understand anything about how modlauncher works and is patching in junk.
