### ISSUE TITLE
Invalid audit trails added when logging excetions

### ISSUE THREAD

**Issue by IzzelAliz** [cpw/modlauncher#44]
When logging an exception that contains classes loaded from child/another classloaders, invalid `re:classloading` trails added to log.

Example code:
```java
        Exception exception = new Exception();
        StackTraceElement[] stackTrace = new StackTraceElement[1];
        stackTrace[0] = new StackTraceElement("test.aa", "test.b", "cc", 111);
        exception.setStackTrace(stackTrace);
        for (int i = 0; i < 3; i++) {
            getLogger().log(Level.SEVERE, "test" + i, exception);
        }
```

gets a log like that:
```
[13:22:20.377] [Server thread/ERROR] [Test/]: test0 java.lang.Exception: null
	at test.aa.test.b(cc:111) ~[?:?] {re:classloading}

[13:22:20.385] [Server thread/ERROR] [Test/]: test1 java.lang.Exception: null
	at test.aa.test.b(cc:111) ~[?:?] {re:classloading,re:classloading}

[13:22:20.386] [Server thread/ERROR] [Test/]: test2 java.lang.Exception: null
	at test.aa.test.b(cc:111) ~[?:?] {re:classloading,re:classloading,re:classloading}
```

**Edit**
It turns out that when logging an exception, log4j wants to load classes that appears in stacktrace. TransformingCL loads it multiple times and thrown multiple times ClassNotFoundException, and add multiple times audit reasons.

Before throwing a ClassNotFoundException, maybe it should remove the reason of this class.
https://github.com/cpw/modlauncher/blob/b1a340bec0f5ab3cb3338c50d4e8add5932ad414/src/main/java/cpw/mods/modlauncher/TransformingClassLoader.java#L252-L256

**Comment by cpw** [comment]
Not an issue, don't do that.

**Comment by IzzelAliz** [comment]
@cpw I believe this **is** an issue.

If you start any server in jdk11, these are printed:

```
[03:17:31] [Forge Version Check/WARN] [ne.mi.fo.VersionChecker/]: Failed to process update information
java.io.IOException: Server returned HTTP response code: 503 for URL: https://gitlab.com/users/sign_in
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969) ~[?:?] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:189) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:206) ~[?:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?] {re:classloading}
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://gitlab.com/users/sign_in
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[?:?] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?] {}
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:173) ~[?:?] {re:classloading}
	... 3 more
```

**Comment by DaemonUmbra** [comment]
Have you tried putting your update json somewhere that doesn't require auth before reading files?
I feel anything further should be run through the forums first.

**Comment by IzzelAliz** [comment]
> Have you tried putting your update json somewhere that doesn't require auth before reading files?
> I feel anything further should be run through the forums first.

That is not my mod. I have 130 mods on my server and there are always 3 or 4 failed their checking.

This is not the point. The point is that everytime modlauncher finding a class it adds the reason regardless of its existence.

**Comment by pau101** [comment]
To further clarify on behalf of Izzel, that error was to show the reported issue occurs naturally in forge, not just an arbitrary construction case. The numerous repeated "re:classloading" trails are evident here:
```
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
```
