### ISSUE TITLE
Unable to get resources which loaded by AppClassLoader.

### ISSUE THREAD

**Issue by ZekerZhayard** [cpw/modlauncher#78]
Consider this test case:
```javascript
var Opcodes = Java.type("org.objectweb.asm.Opcodes");
var InsnList = Java.type("org.objectweb.asm.tree.InsnList");
var InsnNode = Java.type("org.objectweb.asm.tree.InsnNode");
var JumpInsnNode = Java.type("org.objectweb.asm.tree.JumpInsnNode");
var LabelNode = Java.type("org.objectweb.asm.tree.LabelNode");
var MethodInsnNode = Java.type("org.objectweb.asm.tree.MethodInsnNode");
var MethodNode = Java.type("org.objectweb.asm.tree.MethodNode");
var TryCatchBlockNode = Java.type("org.objectweb.asm.tree.TryCatchBlockNode");
var VarInsnNode = Java.type("org.objectweb.asm.tree.VarInsnNode");

function initializeCoreMod() {
    return {
        "MainTransformer": {
            "target": {
                "type": "CLASS",
                "name": "net/minecraft/client/main/Main"
            },
            "transformer": function (cn) {
                cn.methods.add(new MethodNode(Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC, "test", "()Lcpw/mods/niofs/union/UnionFileSystem;", null, null));
                for (var i = 0; i < cn.methods.length; i++) {
                    var method = cn.methods.get(i);
                    if (method.name == "test" && method.desc == "()Lcpw/mods/niofs/union/UnionFileSystem;") {
                        var insnList = new InsnList();
                        insnList.add(new InsnNode(Opcodes.ACONST_NULL));
                        insnList.add(new InsnNode(Opcodes.ARETURN));
                        method.instructions = insnList;
                    } else if (method.name == "main" && method.desc == "([Ljava/lang/String;)V") {
                        var l0 = new LabelNode(), l1 = new LabelNode(), l2 = new LabelNode(), l3 = new LabelNode();
                        var insnList = new InsnList();
                        insnList.add(l0);
                        insnList.add(new InsnNode(Opcodes.ACONST_NULL));
                        insnList.add(new MethodInsnNode(Opcodes.INVOKESTATIC, "net/minecraft/client/main/Main", "test", "()Lcpw/mods/niofs/union/UnionFileSystem;", false));
                        insnList.add(new VarInsnNode(Opcodes.ASTORE, 1));
                        insnList.add(l1);
                        insnList.add(new JumpInsnNode(Opcodes.GOTO, l3));
                        insnList.add(l2);
                        insnList.add(new VarInsnNode(Opcodes.ASTORE, 1));
                        insnList.add(l3);
                        method.instructions.insert(insnList);
                        method.tryCatchBlocks.add(new TryCatchBlockNode(l0, l1, l2, "java/lang/Throwable"));
                    }
                }
                return cn;
            }
        }
    };
}
```

This will get the following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.readShort(ClassReader.java:3585)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:150)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:63)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
	at java.base/java.lang.Class.forName(Class.java:545)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
```

This is because in the `TransformingClassLoader` instance `TRANSFORMER`, both `[packageLookup](https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L231)` and `[parentLoaders](https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L235)` do not contain `cpw.mods.niofs.union` (these two fields also do not contain any ASM/BSL/SJH package names)

**Comment by sciwhiz12** [comment]
This seems to be a combination of Forge's configuration of bootstraplauncher and a possible oversight in securejarhandler's `ModuleClassLoader`.

## Forge's BSL ignore list

bootstraplauncher has an [_ignore list_ of filename prefixes][bsl-ignorelist], where any JAR found on the legacy class path that matches one of these prefixes are ignored and not converted by BSL into a module. This is used to exempt modules who already exist in the JVM (added through the `-p` command-line option) from being converted again into modules, which could cause potential conflicts. 

In Minecraft Forge, these pre-existing modules [are defined][forge-ignoredmodules] to be ASM, securejarhandler, and bootstraplauncher itself. This means these modules are not defined in and are unknown to the `ModuleClassLoader` created by bootstraplauncher. This also means that, when the later `TransformingClassLoader` (who is a subclass of `ModuleClassLoader`) goes to populate its map of package names from parent configurations to their corresponding class loader ([`parentLoaders`][sjh-parentloaders]), it will not find any of ASM, securejarhandler, or bootstraplauncher. This explains why neither `packageLookup` nor `parentLoaders` contain the packages for ASM, BSL, and SJH.

## Oversight in `ModuleClassLoader`

When tracing through the stacktrace, one will see that ModLauncher's [`TransformerClassWriter#computeHierarchyFromFile`][ml-tcw] gets the class bytes from [`TransformingClassLoader#buildTransformedClassNodeFor`][ml-tcl], which simply calls the superclass method [`ModuleClassLoader#getMaybeTransformedClassBytes`][sjh-mcl-getMaybeTransformedClassBytes]. We know from the above that neither `packageLookup` nor `parentLoaders` contains the packages for ASM, BSL, or SJH, which means the queries the information from this map for classes from these packages will not result in anything. 

This leads to the [classloader used to query the classes from these packages to be the *platform class loader*][sjh-mcl-platformcl]. The platform class loader, according to [the javadocs][jdk16-builtinloaders], is _"responsible for loading the platform classes. Platform classes include Java SE platform APIs, their implementation classes and JDK-specific run-time classes that are defined by the platform class loader or its ancestors,"_ and is retrived from `ClassLoader#getPlatformClassLoader`. This is distinct from the *application class loader*, which is available from [`ClassLoader#getSystemClassLoader`][jdk16-systemclassloader] and is _"typically the class loader used to start the application"_. (Here, "system" refers to the running Java virtual machine, which is running and loading the application.)

Because the classes for ASM, BSL, and SJH are on the application class loader and not the platform class loader, `computeHierarchyFromFile` will receive a blank `byte[]` from `buildTransformedClassNodeFor`, which gets passed onto `ClassVisitor`, which then tries to read the magic bytes at the start of the class bytes but fails because it is holding an empty array.

## Solution

Therefore, the solution is that the above error be corrected by changing the use of `ClassLoader.getPlatformClassLoader()` to `ClassLoader.getSystemClassLoader()` instead, so the resolution of class bytes for ASM, SJH, and BSL (or any other class whose module is in the ignore list configured in BSL and exists on the application class loader) works as expected. (I also recommend this issue be filed to the securejarhandler repository instead, or transferred to the securejarhandler repository by a maintainer once that repository is moved into the organization.)

[bsl-ignorelist]: https://github.com/MinecraftForge/bootstraplauncher/blob/ba5f05c32d302a2e66649579188a64bef7dfeef3/src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java#L45-L51
[forge-ignoredmodules]: https://github.com/MinecraftForge/MinecraftForge/blob/41ea5b195bf5c818d1da8932d264a33de16fa632/build.gradle#L256-L262
[sjh-parentloaders]: https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L46-L71

[ml-tcw]: https://github.com/McModLauncher/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L149
[ml-tcl]: https://github.com/McModLauncher/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/TransformingClassLoader.java#L57-L59
[sjh-mcl-getMaybeTransformedClassBytes]: https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L227-L243
[sjh-mcl-platformcl]: https://github.com/MinecraftForge/securejarhandler/blob/f81a31abecf63d567a9741f11a7b227dbb1a45fb/src/main/java/cpw/mods/cl/ModuleClassLoader.java#L235

[jdk16-builtinloaders]: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/ClassLoader.html#builtinLoaders
[jdk16-systemclassloader]: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/ClassLoader.html#getSystemClassLoader()
